# Generated by Django 4.1.7 on 2023-04-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0002_rename_createddate_cart_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakereview', to='cakestore.cake'),
        ),
    ]
