# Generated by Django 4.1.7 on 2023-05-03 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0003_rename_products_cart_product_alter_cake_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2023, 5, 8)),
        ),
    ]
