# Generated by Django 4.1.7 on 2023-05-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakestore', '0004_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_date',
            new_name='ordered_date',
        ),
    ]
